### ISSUE TITLE
Setting the path

### ISSUE THREAD

**Issue by RyanLutz** [badsyntax/atom-sassbeautify#1]
If possible, could you elaborate more on how to install. 

You said "If are you using a ruby version manager, you will need to set the PATH in the package settings: Preferences >> Sassbeautify >> Path. (To get the PATH, open up a new shell and type echo $PATH.)" 
When I "echo $PATH" I get about 15 different paths and half of them reference ruby in some way. Am I specifying a path to the gems (/bin), or the gem itself? 

I'm getting this error: 

"There was an error converting your sass:
execvp(): No such file or directory"

in the console
Uncaught Error: write EPIPE events.js:82
Uncaught Error: spawn ENOENT events.js:82

Tards like myself need more robust documentation.

**Comment by badsyntax** [comment]
Just use the entire path.

**Comment by badsyntax** [comment]
Yea, about the documentation, this project was just a test project to get familiar with Atom, I wasn't aware many people were using it. I'll update the docs soon, thanks for creating the issue.

**Comment by RyanLutz** [comment]
Jees. Wasn't expecting such a quick response! Thanks much!

**Comment by badsyntax** [comment]
Cool! Does using the entire path fix things for you?

**Comment by RyanLutz** [comment]
Yes! works brilliantly

**Comment by badsyntax** [comment]
Great :+1:
