### ISSUE TITLE
Beautify fails to run on Laravel Blade/PHP Pages

### ISSUE THREAD

**Issue by maxxcrawford** [badsyntax/atom-sassbeautify#3]
Using [Laravel Blade Template Structure](http://laravel.com/docs/4.2/templates) on project. The plug-in fails when ran on foo.blade.php files. It may be that the page starts with Laravel specific syntax, `@layout` or `@section('bar')` before the standard HTML beings. 

**Atom Error Code:**

```
Command failed: /bin/sh -c [ -f ~/.bash_profile ] && source ~/.bash_profile;[ -f ~/.bashrc ] && source ~/.bashrc;php_beautifier "/var/folders/vp/_9mdqt253m5bjm29_mbj7_rr0000gn/T/input11491-14187-1sd36l1" "/var/folders/vp/_9mdqt253m5bjm29_mbj7_rr0000gn/T/11491-14187-1r4cq45" /bin/sh: php_beautifier: command not found
```

**Comment by maxxcrawford** [comment]
…and I posted this on the wrong plug-in. Sorry!

**Comment by badsyntax** [comment]
hehe :) no probs
